name: demo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/1.png
    - assets/icons/back_button.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
